name: Close Stale Issues
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  auto-close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check for stale issues
        uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically closed due to inactivity. Feel free to reopen if you still face this problem.'
          stale-pr-message: 'This pull request has been automatically closed due to inactivity. Feel free to reopen if you still want to merge this change.'
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          days-before-issue-stale: 60
          days-before-issue-close: 14
          stale-issue-label: "stale"
          exempt-issue-labels: 'in-progress'
